CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '租户ID',
    code VARCHAR(64) NOT NULL UNIQUE COMMENT '租户唯一编码',
    name VARCHAR(128) NOT NULL COMMENT '租户名称',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0禁用',
    plan_code VARCHAR(64) NULL COMMENT '套餐编码',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户主表';

CREATE TABLE IF NOT EXISTS tenant_domains (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '租户域名ID',
    tenant_id BIGINT UNSIGNED NOT NULL COMMENT '租户ID',
    domain VARCHAR(255) NOT NULL UNIQUE COMMENT '绑定域名',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0禁用',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CONSTRAINT fk_tenant_domains_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户域名表';

CREATE TABLE IF NOT EXISTS applications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '应用ID',
    code VARCHAR(64) NOT NULL UNIQUE COMMENT '应用编码',
    name VARCHAR(128) NOT NULL COMMENT '应用名称',
    entry_path VARCHAR(255) NOT NULL COMMENT '应用入口路径或Provider路径',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0禁用',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='应用登记表';

CREATE TABLE IF NOT EXISTS plugins (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '插件ID',
    code VARCHAR(64) NOT NULL UNIQUE COMMENT '插件编码',
    name VARCHAR(128) NOT NULL COMMENT '插件名称',
    version VARCHAR(32) NOT NULL DEFAULT '0.1.0' COMMENT '插件版本号',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0禁用',
    config JSON NULL COMMENT '插件全局JSON配置',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='插件登记表';

CREATE TABLE IF NOT EXISTS system_settings (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '系统配置ID',
    setting_key VARCHAR(128) NOT NULL UNIQUE COMMENT '配置键',
    setting_value JSON NULL COMMENT '配置JSON值',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统公共配置表';

CREATE TABLE IF NOT EXISTS tenant_plugin_settings (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '租户插件配置ID',
    tenant_id BIGINT UNSIGNED NOT NULL COMMENT '租户ID',
    plugin_code VARCHAR(64) NOT NULL COMMENT '插件编码',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '租户是否启用插件：1启用，0禁用',
    config JSON NULL COMMENT '租户插件JSON配置',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_tenant_plugin (tenant_id, plugin_code),
    CONSTRAINT fk_tenant_plugin_settings_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户插件启用与配置表';

CREATE TABLE IF NOT EXISTS tenant_applications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '租户应用配置ID',
    tenant_id BIGINT UNSIGNED NOT NULL COMMENT '租户ID',
    application_code VARCHAR(64) NOT NULL COMMENT '应用编码',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '租户是否启用应用：1启用，0禁用',
    config JSON NULL COMMENT '租户应用JSON配置',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_tenant_application (tenant_id, application_code),
    CONSTRAINT fk_tenant_applications_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户应用启用与配置表';
